=== MarcPantel/tom/examples/xquery/xqueryimpl/xquery/data/uc4.dtd
<!DOCTYPE users [
  <!ELEMENT users   (user_tuple*)>
  <!ELEMENT user_tuple (userid, name, rating?)>
  <!ELEMENT userid  (#PCDATA)>
  <!ELEMENT name    (#PCDATA)>
  <!ELEMENT rating  (#PCDATA)>
]>

<!DOCTYPE items [
  <!ELEMENT items       (item_tuple*)>
  <!ELEMENT item_tuple  (itemno, description, offered_by, 
                              start_date?, end_date?, reserve_price? )>
  <!ELEMENT itemno      (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT offered_by  (#PCDATA)>
  <!ELEMENT start_date  (#PCDATA)>
  <!ELEMENT end_date    (#PCDATA)>
  <!ELEMENT reserve_price (#PCDATA)>
]>

<!DOCTYPE bids [
  <!ELEMENT bids      (bid_tuple*)>
  <!ELEMENT bid_tuple (userid, itemno, bid, bid_date)>
  <!ELEMENT userid    (#PCDATA)>
  <!ELEMENT itemno    (#PCDATA)>
  <!ELEMENT bid       (#PCDATA)>
  <!ELEMENT bid_date  (#PCDATA)>
]>

=== MarcPantel/tom/examples/xquery/uc4/users.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE users SYSTEM "uc4.dtd" >

<users>
  <user_tuple>
    <userid>U01</userid>
    <name>Tom Jones</name>
    <rating>B</rating>
  </user_tuple>

  <user_tuple>
    <userid>U02</userid>
    <name>Marry Doe</name>
    <rating>A</rating>
  </user_tuple>

  <user_tuple>
    <userid>U03</userid>
    <name>Dee Linguent</name>
    <rating>D</rating>
  </user_tuple>

  <user_tuple>
    <userid>U04</userid>
    <name>Roger Smith</name>
    <rating>C</rating>
  </user_tuple>

  <user_tuple>
    <userid>U05</userid>
    <name>Jack Sprat</name>
    <rating>B</rating>
  </user_tuple>

  <user_tuple>
    <userid>U06</userid>
    <name>Rip Van Kinkle</name>
    <rating>B</rating>
  </user_tuple>

</users>
