<?xml version="1.0" standalone="no"?>

<!DOCTYPE users [
  <!ELEMENT users   (user_tuple*)>
  <!ELEMENT user_tuple (userid, name, rating?)>
  <!ELEMENT userid  (#PCDATA)>
  <!ELEMENT name    (#PCDATA)>
  <!ELEMENT rating  (#PCDATA)>
]>

<users>
  <user_tuple>
    <userid>U01</userid>
    <name>Tom Jones</name>
    <rating>B</rating>
  </user_tuple>

  <user_tuple>
    <userid>U02</userid>
    <name>Marry Doe</name>
    <rating>A</rating>
  </user_tuple>

  <user_tuple>
    <userid>U03</userid>
    <name>Dee Linguent</name>
    <rating>D</rating>
  </user_tuple>

  <user_tuple>
    <userid>U04</userid>
    <name>Roger Smith</name>
    <rating>C</rating>
  </user_tuple>

  <user_tuple>
    <userid>U05</userid>
    <name>Jack Sprat</name>
    <rating>B</rating>
  </user_tuple>

  <user_tuple>
    <userid>U06</userid>
    <name>Rip Van Kinkle</name>
    <rating>B</rating>
  </user_tuple>

</users>